services:
  - type: web
    name: topper-finder
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
